openapi: 3.0.0
info:
  title: Sample API
  description: This is a sample API documentation.
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/users:
    get:
      summary: Get all users
      description: Retrieves a list of all users.
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
              example:
                - id: 1
                  name: John Doe
                  email: john@example.com
                - id: 2
                  name: Jane Smith
                  email: jane@example.com